version: "2"

services:
    mysql:
        container_name: bims-mysql
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=bims
            - MYSQL_ROOT_PASSWORD=root
        restart: always

    webserver:
        image: nginx:alpine
        container_name: bims-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    bims-php-fpm:
        build:
            context: ./dev
            dockerfile: Dockerfile
        container_name: bims-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./dev/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
            
    myadmin:
        container_name: myadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 5000:80
        volumes:
            - ./php-make/upload.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
        restart: always


volumes:
  db-data: